services:
  singula-app:
    container_name: singula-app
    hostname: singula-app
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - singula

  singula-api:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: singula-api
    hostname: singula-api
    restart: unless-stopped
    volumes:
      - ./api:/api
      - ./api/data:/pb_data
    networks:
      - singula

networks:
  singula:
    external: true
