services:
  singula:
    container_name: singula-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5173:3000
    networks:
      - singula

  singulaapi:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: singula-api
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./api:/api
      - ./api/data:/pb_data
    networks:
      - singula

networks:
  singula:
